prod-devel-agl plus graphic binary
one issue exists
Error: Transaction check error:
  file /usr/local conflicts between attempted installs of rcar-proprietary-graphic-1.9-r0.h3ulcb_4x2g_kf_xt and base-files-3.0.14-r89.h3ulcb_4x2g_kf_xt

Signed-off-by: xen-troops-buildbot <not.real.email@epam.com>